[workspace]
members = [
    "crates/slimblade-image",
    "crates/slimblade-protocol",
    "crates/slimblade-verify",
    "xtask",
]
exclude = ["firmware/bk3635-rs"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "Apache-2.0"
rust-version = "1.97.1"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
warnings = "deny"

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
undocumented_unsafe_blocks = "deny"
unwrap_used = "deny"
